### ISSUE TITLE
Yahoo Login Error

### ISSUE THREAD

**Issue by nish-patel** [philipfong/free-agent-sleeper#3]
I get this error when trying to run it

Failure/Error: find('#login-username').set(username)
     
     Selenium::WebDriver::Error::UnknownError:
       unknown error: call function result missing 'value'
         (Session info: chrome=68.0.3440.106)
         (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.6 x86_64)

**Comment by philipfong** [comment]
Try updating to the latest ChromeDriver. You should be able to just type `chromedriver-update` from your terminal.
