### ISSUE TITLE
Yahoo Authentication doesn't allow this script to run

### ISSUE THREAD

**Issue by ccolligan** [philipfong/free-agent-sleeper#6]
The authentication code keeps the script from logging you in. No longer functional.

**Comment by philipfong** [comment]
Can you provide some specifics as to what error you're seeing?

**Comment by philipfong** [comment]
Sorry, there's nothing that this script (or any script for that matter) can do about that. You'll have to disable 2-step authentication on your Yahoo account if you want to leverage something like this.
